services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    user: root
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - N8N_BLOCK_FILE_ACCESS_TO_N8N=false
      - GENERIC_TIMEZONE=Asia/Hong_Kong
      - TZ=Asia/Hong_Kong
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=internal
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
      
      # 🔥 改呢行 - 用 n8n 預設嘅 allowed path
      - MEMORY_PATH=/root/.n8n-files/brian/memory/summary.md
      - N8N_RESTRICT_FILE_ACCESS_TO=
      - N8N_ENCRYPTION_KEY=comp3520-super-secret-key-2026
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - NODE_FUNCTION_ALLOW_BUILTIN=fs,path
      - NODES_EXCLUDE="[]"
    
    volumes:
      - n8n_data:/home/node/.n8n
      
      # 🔥 改呢行 - mount 去 n8n 預設 path
      - ./../../:/root/.n8n-files
    
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: whisper
    ports:
      - "8000:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=faster_whisper
      - PYTHONUNBUFFERED=1
      - ALLOW_ORIGINS=*

  tts:
    image: synesthesiam/coqui-tts
    container_name: tts
    ports:
      - "5010:5000"
    entrypoint: ["tts-server"]
    command: ["--model_name", "tts_models/en/ljspeech/tacotron2-DDC", "--port", "5000"]
    environment:
      - PYTHONUNBUFFERED=1
              
volumes:
  n8n_data:
  postgres_data:
  ollama_data:
